version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - $PWD/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - net-school

  web2py:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - net-school

networks:
  net-school:

