#version used
FROM node:20

#create folder
WORKDIR /app

#project libraries
COPY package*.json ./

#install the libraries
RUN npm install

#copy the project files
COPY . .

#service port
EXPOSE 3000

#start application
CMD [ "npm", "start" ]